In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!unzip "/content/drive/MyDrive/GdriveXbot/16cbaf00248311ed.zip"

Streaming output truncated to the last 5000 lines.
  inflating: dataset/test/50564.txt
  inflating: dataset/test/50571.txt
  inflating: dataset/test/50581.txt
  inflating: dataset/test/50583.txt
  inflating: dataset/test/50587.txt
  inflating: dataset/test/50603.txt
  inflating: dataset/test/50609.txt
  inflating: dataset/test/50612.txt
  inflating: dataset/test/50617.txt
  inflating: dataset/test/50628.txt
  inflating: dataset/test/50644.txt
  inflating: dataset/test/50647.txt
  inflating: dataset/test/50650.txt
  inflating: dataset/test/50658.txt
  inflating: dataset/test/50697.txt
  inflating: dataset/test/50698.txt
  inflating: dataset/test/50705.txt
  inflating: dataset/test/50723.txt
  inflating: dataset/test/50728.txt
  inflating: dataset/test/50733.txt
  inflating: dataset/test/50746.txt
  inflating: dataset/test/50750.txt
  inflating: dataset/test/50769.txt
  inflating: dataset/test/50780.txt
  inflating: dataset/test/50786.txt
  inflating: dataset/test/50796.txt
  inflating: dataset/test/50798.txt
  inflating: dataset/test/50827.txt
  inflating: dataset/test/50831.txt
  inflating: dataset/test/50835.txt
  inflating: dataset/test/50860.txt
  inflating: dataset/test/50913.txt
  inflating: dataset/test/50915.txt
  inflating: dataset/test/50925.txt
  inflating: dataset/test/50936.txt
  inflating: dataset/test/50960.txt
  inflating: dataset/test/50963.txt
  inflating: dataset/test/50977.txt
  inflating: dataset/test/50987.txt
  inflating: dataset/test/50994.txt
  inflating: dataset/test/51011.txt
  inflating: dataset/test/51019.txt
  inflating: dataset/test/51030.txt
  inflating: dataset/test/51035.txt
  inflating: dataset/test/51043.txt
  inflating: dataset/test/51056.txt
  inflating: dataset/test/51063.txt
  inflating: dataset/test/51067.txt
  inflating: dataset/test/51085.txt
  inflating: dataset/test/51098.txt
  inflating: dataset/test/51113.txt
  inflating: dataset/test/51120.txt
  inflating: dataset/test/51131.txt
  inflating: dataset/test/51133.txt
  inflating: dataset/test/51135.txt
  inflating: dataset/test/51148.txt
  inflating: dataset/test/51153.txt
  inflating: dataset/test/51171.txt
  inflating: dataset/test/51172.txt
  inflating: dataset/test/51176.txt
  inflating: dataset/test/51178.txt
  inflating: dataset/test/51181.txt
  inflating: dataset/test/51183.txt
  inflating: dataset/test/51189.txt
  inflating: dataset/test/51221.txt
  inflating: dataset/test/51235.txt
  inflating: dataset/test/51242.txt
  inflating: dataset/test/51265.txt
  inflating: dataset/test/51269.txt
  inflating: dataset/test/51281.txt
  inflating: dataset/test/51307.txt
  inflating: dataset/test/51317.txt
  inflating: dataset/test/51329.txt
  inflating: dataset/test/51333.txt
  inflating: dataset/test/51351.txt
  inflating: dataset/test/51352.txt
  inflating: dataset/test/51354.txt
  inflating: dataset/test/51369.txt
  inflating: dataset/test/51411.txt
  inflating: dataset/test/51420.txt
  inflating: dataset/test/51437.txt
  inflating: dataset/test/51445.txt
  inflating: dataset/test/51447.txt
  inflating: dataset/test/51467.txt
  inflating: dataset/test/51480.txt
  inflating: dataset/test/51497.txt
  inflating: dataset/test/51512.txt
  inflating: dataset/test/51518.txt
  inflating: dataset/test/51534.txt
  inflating: dataset/test/51536.txt
  inflating: dataset/test/51543.txt
  inflating: dataset/test/51548.txt
  inflating: dataset/test/51549.txt
  inflating: dataset/test/51551.txt
  inflating: dataset/test/51555.txt
  inflating: dataset/test/51556.txt
  inflating: dataset/test/51582.txt
  inflating: dataset/test/51586.txt
  inflating: dataset/test/51596.txt
  inflating: dataset/test/51609.txt
  inflating: dataset/test/51619.txt
  inflating: dataset/test/51625.txt
  inflating: dataset/test/51636.txt
  inflating: dataset/test/51647.txt
  inflating: dataset/test/51653.txt
  inflating: dataset/test/51654.txt
  inflating: dataset/test/51673.txt
  inflating: dataset/test/51696.txt
  inflating: dataset/test/51705.txt
  inflating: dataset/test/51706.txt
  inflating: dataset/test/51728.txt
  inflating: dataset/test/51734.txt
  inflating: dataset/test/51735.txt
  inflating: dataset/test/51742.txt
  inflating: dataset/test/51743.txt
  inflating: dataset/test/51762.txt
  inflating: dataset/test/51775.txt
  inflating: dataset/test/51788.txt
  inflating: dataset/test/51795.txt
  inflating: dataset/test/51797.txt
  inflating: dataset/test/51811.txt
  inflating: dataset/test/51815.txt
  inflating: dataset/test/51826.txt
  inflating: dataset/test/51831.txt
  inflating: dataset/test/51846.txt
  inflating: dataset/test/51860.txt
  inflating: dataset/test/51866.txt
  inflating: dataset/test/51869.txt
  inflating: dataset/test/51882.txt
  inflating: dataset/test/51890.txt
  inflating: dataset/test/51905.txt
  inflating: dataset/test/51914.txt
  inflating: dataset/test/51922.txt
  inflating: dataset/test/51928.txt
  inflating: dataset/test/51941.txt
  inflating: dataset/test/51949.txt
  inflating: dataset/test/51953.txt
  inflating: dataset/test/51958.txt
  inflating: dataset/test/51968.txt
  inflating: dataset/test/51994.txt
  inflating: dataset/test/51997.txt
  inflating: dataset/test/52012.txt
  inflating: dataset/test/52013.txt
  inflating: dataset/test/52016.txt
  inflating: dataset/test/52019.txt
  inflating: dataset/test/52034.txt
  inflating: dataset/test/52037.txt
  inflating: dataset/test/52038.txt
  inflating: dataset/test/52042.txt
  inflating: dataset/test/52050.txt
  inflating: dataset/test/52060.txt
  inflating: dataset/test/52084.txt
  inflating: dataset/test/52089.txt
  inflating: dataset/test/52099.txt
  inflating: dataset/test/52104.txt
  inflating: dataset/test/52132.txt
  inflating: dataset/test/52140.txt
  inflating: dataset/test/52143.txt
  inflating: dataset/test/52152.txt
  inflating: dataset/test/52159.txt
  inflating: dataset/test/52169.txt
  inflating: dataset/test/52200.txt
  inflating: dataset/test/52209.txt
  inflating: dataset/test/52282.txt
  inflating: dataset/test/52310.txt
  inflating: dataset/test/52319.txt
  inflating: dataset/test/52320.txt
  inflating: dataset/test/52326.txt
  inflating: dataset/test/52336.txt
  inflating: dataset/test/52339.txt
  inflating: dataset/test/52350.txt
  inflating: dataset/test/52359.txt
  inflating: dataset/test/52360.txt
  inflating: dataset/test/52361.txt
  inflating: dataset/test/52368.txt
  inflating: dataset/test/52374.txt
  inflating: dataset/test/52423.txt
  inflating: dataset/test/52436.txt
  inflating: dataset/test/52439.txt
  inflating: dataset/test/52452.txt
  inflating: dataset/test/52458.txt
  inflating: dataset/test/52462.txt
  inflating: dataset/test/52476.txt
  inflating: dataset/test/52496.txt
  inflating: dataset/test/52499.txt
  inflating: dataset/test/52504.txt
  inflating: dataset/test/52512.txt
  inflating: dataset/test/52516.txt
  inflating: dataset/test/52546.txt
  inflating: dataset/test/52549.txt
  inflating: dataset/test/52562.txt
  inflating: dataset/test/52578.txt
  inflating: dataset/test/52579.txt
  inflating: dataset/test/52581.txt
  inflating: dataset/test/52586.txt
  inflating: dataset/test/52609.txt
  inflating: dataset/test/52616.txt
  inflating: dataset/test/52627.txt
  inflating: dataset/test/52630.txt
  inflating: dataset/test/52634.txt
  inflating: dataset/test/52640.txt
  inflating: dataset/test/52649.txt
  inflating: dataset/test/52650.txt
  inflating: dataset/test/52658.txt
  inflating: dataset/test/52668.txt
  inflating: dataset/test/52673.txt
  inflating: dataset/test/52676.txt
  inflating: dataset/test/52688.txt
  inflating: dataset/test/52701.txt
  inflating: dataset/test/52707.txt
  inflating: dataset/test/52709.txt
  inflating: dataset/test/52747.txt
  inflating: dataset/test/52764.txt
  inflating: dataset/test/52790.txt
  inflating: dataset/test/52801.txt
  inflating: dataset/test/52804.txt
  inflating: dataset/test/52826.txt
  inflating: dataset/test/52828.txt
  inflating: dataset/test/52845.txt
  inflating: dataset/test/52863.txt
  inflating: dataset/test/52875.txt
  inflating: dataset/test/52902.txt
  inflating: dataset/test/52903.txt
  inflating: dataset/test/52915.txt
  inflating: dataset/test/52935.txt
  inflating: dataset/test/52966.txt
  inflating: dataset/test/52967.txt
  inflating: dataset/test/52977.txt
  inflating: dataset/test/52989.txt
  inflating: dataset/test/52991.txt
  inflating: dataset/test/52992.txt
  inflating: dataset/test/53010.txt
  inflating: dataset/test/53021.txt
  inflating: dataset/test/53059.txt
  inflating: dataset/test/53062.txt
  inflating: dataset/test/53066.txt
  inflating: dataset/test/53087.txt
  inflating: dataset/test/53121.txt
  inflating: dataset/test/53123.txt
  inflating: dataset/test/53125.txt
  inflating: dataset/test/53132.txt
  inflating: dataset/test/53134.txt
  inflating: dataset/test/53143.txt
  inflating: dataset/test/53144.txt
  inflating: dataset/test/53145.txt
  inflating: dataset/test/53169.txt
  inflating: dataset/test/53170.txt
  inflating: dataset/test/53176.txt
  inflating: dataset/test/53178.txt
  inflating: dataset/test/53182.txt
  inflating: dataset/test/53195.txt
  inflating: dataset/test/53215.txt
  inflating: dataset/test/53217.txt
  inflating: dataset/test/53227.txt
  inflating: dataset/test/53228.txt
  inflating: dataset/test/53231.txt
  inflating: dataset/test/53236.txt
  inflating: dataset/test/53240.txt
  inflating: dataset/test/53287.txt
  inflating: dataset/test/53308.txt
  inflating: dataset/test/53359.txt
  inflating: dataset/test/53363.txt
  inflating: dataset/test/53365.txt
  inflating: dataset/test/53367.txt
  inflating: dataset/test/53381.txt
  inflating: dataset/test/53403.txt
  inflating: dataset/test/53405.txt
  inflating: dataset/test/53427.txt
  inflating: dataset/test/53437.txt
  inflating: dataset/test/53448.txt
  inflating: dataset/test/53463.txt
  inflating: dataset/test/53464.txt
  inflating: dataset/test/53480.txt
  inflating: dataset/test/53483.txt
  inflating: dataset/test/53487.txt
  inflating: dataset/test/53505.txt
  inflating: dataset/test/53509.txt
  inflating: dataset/test/53511.txt
  inflating: dataset/test/53514.txt
  inflating: dataset/test/53519.txt
  inflating: dataset/test/53520.txt
  inflating: dataset/test/53539.txt
  inflating: dataset/test/53545.txt
  inflating: dataset/test/53553.txt
  inflating: dataset/test/53563.txt
  inflating: dataset/test/53576.txt
  inflating: dataset/test/53590.txt
  inflating: dataset/test/53602.txt
  inflating: dataset/test/53603.txt
  inflating: dataset/test/53607.txt
  inflating: dataset/test/53616.txt
  inflating: dataset/test/53627.txt
  inflating: dataset/test/53653.txt
  inflating: dataset/test/53680.txt
  inflating: dataset/test/53681.txt
  inflating: dataset/test/53684.txt
  inflating: dataset/test/53696.txt
  inflating: dataset/test/53716.txt
  inflating: dataset/test/53718.txt
  inflating: dataset/test/53722.txt
  inflating: dataset/test/53725.txt
  inflating: dataset/test/53728.txt
  inflating: dataset/test/53745.txt
  inflating: dataset/test/53752.txt
  inflating: dataset/test/53760.txt
  inflating: dataset/test/53768.txt
  inflating: dataset/test/53780.txt
  inflating: dataset/test/53801.txt
  inflating: dataset/test/53822.txt
  inflating: dataset/test/53827.txt
  inflating: dataset/test/53856.txt
  inflating: dataset/test/53862.txt
  inflating: dataset/test/53895.txt
  inflating: dataset/test/53898.txt
  inflating: dataset/test/53907.txt
  inflating: dataset/test/53909.txt
  inflating: dataset/test/53913.txt
  inflating: dataset/test/53963.txt
  inflating: dataset/test/53972.txt
  inflating: dataset/test/53976.txt
  inflating: dataset/test/53987.txt
  inflating: dataset/test/53993.txt
  inflating: dataset/test/54005.txt
  inflating: dataset/test/54022.txt
  inflating: dataset/test/54024.txt
  inflating: dataset/test/54028.txt
  inflating: dataset/test/54043.txt
  inflating: dataset/test/54049.txt
  inflating: dataset/test/54081.txt
  inflating: dataset/test/54088.txt
  inflating: dataset/test/54093.txt
  inflating: dataset/test/54119.txt
  inflating: dataset/test/54152.txt
  inflating: dataset/test/54166.txt
  inflating: dataset/test/54169.txt
  inflating: dataset/test/54175.txt
  inflating: dataset/test/54186.txt
  inflating: dataset/test/54189.txt
  inflating: dataset/test/54192.txt
  inflating: dataset/test/54200.txt
  inflating: dataset/test/54222.txt
  inflating: dataset/test/54227.txt
  inflating: dataset/test/54229.txt
  inflating: dataset/test/54238.txt
  inflating: dataset/test/54252.txt
  inflating: dataset/test/54268.txt
  inflating: dataset/test/54271.txt
  inflating: dataset/test/54334.txt
  inflating: dataset/test/54347.txt
  inflating: dataset/test/54364.txt
  inflating: dataset/test/54368.txt
  inflating: dataset/test/54372.txt
  inflating: dataset/test/54374.txt
  inflating: dataset/test/54377.txt
  inflating: dataset/test/54379.txt
  inflating: dataset/test/54383.txt
  inflating: dataset/test/54390.txt
  inflating: dataset/test/54395.txt
  inflating: dataset/test/54396.txt
  inflating: dataset/test/54405.txt
  inflating: dataset/test/54411.txt
  inflating: dataset/test/54416.txt
  inflating: dataset/test/54446.txt
  inflating: dataset/test/54450.txt
  inflating: dataset/test/54463.txt
  inflating: dataset/test/54477.txt
  inflating: dataset/test/54502.txt
  inflating: dataset/test/54508.txt
  inflating: dataset/test/54511.txt
  inflating: dataset/test/54516.txt
  inflating: dataset/test/54536.txt
  inflating: dataset/test/54539.txt
  inflating: dataset/test/54563.txt
  inflating: dataset/test/54603.txt
  inflating: dataset/test/54610.txt
  inflating: dataset/test/54617.txt
  inflating: dataset/test/54620.txt
  inflating: dataset/test/54625.txt
  inflating: dataset/test/54638.txt
  inflating: dataset/test/54641.txt
  inflating: dataset/test/54650.txt
  inflating: dataset/test/54672.txt
  inflating: dataset/test/54680.txt
  inflating: dataset/test/54684.txt
  inflating: dataset/test/54685.txt
  inflating: dataset/test/54693.txt
  inflating: dataset/test/54699.txt
  inflating: dataset/test/54703.txt
  inflating: dataset/test/54704.txt
  inflating: dataset/test/54712.txt
  inflating: dataset/test/54728.txt
  inflating: dataset/test/54729.txt
  inflating: dataset/test/54732.txt
  inflating: dataset/test/54733.txt
  inflating: dataset/test/54757.txt
  inflating: dataset/test/54763.txt
  inflating: dataset/test/54765.txt
  inflating: dataset/test/54775.txt
  inflating: dataset/test/54792.txt
  inflating: dataset/test/54827.txt
  inflating: dataset/test/54843.txt
  inflating: dataset/test/54846.txt
  inflating: dataset/test/54849.txt
  inflating: dataset/test/54855.txt
  inflating: dataset/test/54867.txt
  inflating: dataset/test/54875.txt
  inflating: dataset/test/54882.txt
  inflating: dataset/test/54916.txt
  inflating: dataset/test/54928.txt
  inflating: dataset/test/54942.txt
  inflating: dataset/test/54948.txt
  inflating: dataset/test/54967.txt
  inflating: dataset/test/54996.txt
  inflating: dataset/test/54997.txt
  inflating: dataset/test/55016.txt
  inflating: dataset/test/55031.txt
  inflating: dataset/test/55035.txt
  inflating: dataset/test/55047.txt
  inflating: dataset/test/55051.txt
  inflating: dataset/test/55055.txt
  inflating: dataset/test/55074.txt
  inflating: dataset/test/55086.txt
  inflating: dataset/test/55087.txt
  inflating: dataset/test/55092.txt
  inflating: dataset/test/55117.txt
  inflating: dataset/test/55118.txt
  inflating: dataset/test/55149.txt
  inflating: dataset/test/55165.txt
  inflating: dataset/test/55167.txt
  inflating: dataset/test/55184.txt
  inflating: dataset/test/55193.txt
  inflating: dataset/test/55195.txt
  inflating: dataset/test/55203.txt
  inflating: dataset/test/55204.txt
  inflating: dataset/test/55207.txt
  inflating: dataset/test/55215.txt
  inflating: dataset/test/55216.txt
  inflating: dataset/test/55236.txt
  inflating: dataset/test/55260.txt
  inflating: dataset/test/55280.txt
  inflating: dataset/test/55281.txt
  inflating: dataset/test/55284.txt
  inflating: dataset/test/55296.txt
  inflating: dataset/test/55308.txt
  inflating: dataset/test/55311.txt
  inflating: dataset/test/55344.txt
  inflating: dataset/test/55346.txt
  inflating: dataset/test/55368.txt
  inflating: dataset/test/55390.txt
  inflating: dataset/test/55400.txt
  inflating: dataset/test/55406.txt
  inflating: dataset/test/55412.txt
  inflating: dataset/test/55421.txt
  inflating: dataset/test/55426.txt
  inflating: dataset/test/55446.txt
  inflating: dataset/test/55450.txt
  inflating: dataset/test/55466.txt
  inflating: dataset/test/55467.txt
  inflating: dataset/test/55472.txt
  inflating: dataset/test/55481.txt
  inflating: dataset/test/55483.txt
  inflating: dataset/test/55519.txt
  inflating: dataset/test/55538.txt
  inflating: dataset/test/55559.txt
  inflating: dataset/test/55571.txt
  inflating: dataset/test/55574.txt
  inflating: dataset/test/55607.txt
  inflating: dataset/test/55626.txt
  inflating: dataset/test/55634.txt
  inflating: dataset/test/55638.txt
  inflating: dataset/test/55644.txt
  inflating: dataset/test/55648.txt
  inflating: dataset/test/55654.txt
  inflating: dataset/test/55661.txt
  inflating: dataset/test/55669.txt
  inflating: dataset/test/55675.txt
  inflating: dataset/test/55681.txt
  inflating: dataset/test/55687.txt
  inflating: dataset/test/55703.txt
  inflating: dataset/test/55706.txt
  inflating: dataset/test/55715.txt
  inflating: dataset/test/55745.txt
  inflating: dataset/test/55763.txt
  inflating: dataset/test/55765.txt
  inflating: dataset/test/55767.txt
  inflating: dataset/test/55768.txt
  inflating: dataset/test/55784.txt
  inflating: dataset/test/55824.txt
  inflating: dataset/test/55830.txt
  inflating: dataset/test/55845.txt
  inflating: dataset/test/55860.txt
  inflating: dataset/test/55873.txt
  inflating: dataset/test/55878.txt
  inflating: dataset/test/55892.txt
  inflating: dataset/test/55897.txt
  inflating: dataset/test/55907.txt
  inflating: dataset/test/55918.txt
  inflating: dataset/test/55928.txt
  inflating: dataset/test/55930.txt
  inflating: dataset/test/55961.txt
  inflating: dataset/test/55986.txt
  inflating: dataset/test/55987.txt
  inflating: dataset/test/55997.txt
  inflating: dataset/test/56006.txt
  inflating: dataset/test/56012.txt
  inflating: dataset/test/56024.txt
  inflating: dataset/test/56035.txt
  inflating: dataset/test/56040.txt
  inflating: dataset/test/56053.txt
  inflating: dataset/test/56081.txt
  inflating: dataset/test/56110.txt
  inflating: dataset/test/56112.txt
  inflating: dataset/test/56139.txt
  inflating: dataset/test/56153.txt
  inflating: dataset/test/56185.txt
  inflating: dataset/test/56199.txt
  inflating: dataset/test/56207.txt
  inflating: dataset/test/56234.txt
  inflating: dataset/test/56235.txt
  inflating: dataset/test/56242.txt
  inflating: dataset/test/56259.txt
  inflating: dataset/test/56260.txt
  inflating: dataset/test/56266.txt
  inflating: dataset/test/56268.txt
  inflating: dataset/test/56270.txt
  inflating: dataset/test/56283.txt
  inflating: dataset/test/56286.txt
  inflating: dataset/test/56288.txt
  inflating: dataset/test/56293.txt
  inflating: dataset/test/56343.txt
  inflating: dataset/test/56366.txt
  inflating: dataset/test/56370.txt
  inflating: dataset/test/56378.txt
  inflating: dataset/test/56397.txt
  inflating: dataset/test/56398.txt
  inflating: dataset/test/56403.txt
  inflating: dataset/test/56426.txt
  inflating: dataset/test/56446.txt
  inflating: dataset/test/56475.txt
  inflating: dataset/test/56487.txt
  inflating: dataset/test/56497.txt
  inflating: dataset/test/56498.txt
  inflating: dataset/test/56512.txt
  inflating: dataset/test/56516.txt
  inflating: dataset/test/56518.txt
  inflating: dataset/test/56523.txt
  inflating: dataset/test/56530.txt
  inflating: dataset/test/56533.txt
  inflating: dataset/test/56535.txt
  inflating: dataset/test/56540.txt
  inflating: dataset/test/56553.txt
  inflating: dataset/test/56559.txt
  inflating: dataset/test/56573.txt
  inflating: dataset/test/56600.txt

In [ ]:
import glob
with open('test.csv', 'a') as csv_file:
    for path in glob.glob('/content/dataset/test*.txt'):
        with open(path) as txt_file:
            txt = txt_file.read() + '\n'
            csv_file.write(txt)

In [ ]:
import glob
with open('train.csv', 'a') as csv_file:
    for path in glob.glob('/content/dataset/train/*.txt'):
        with open(path) as txt_file:
            txt = txt_file.read() + '\n'
            csv_file.write(txt)

In [ ]:
path='/content/dataset/train/0.txt'

In [ ]:
name=[]

In [ ]:
s=[]

In [ ]:
v=[]

In [ ]:
f=open(path,"r")
lines=f.readlines()
result=[]
for x in lines:
    b=x.split()
    result.append(b[1])

In [ ]:
name=[]

In [ ]:
f=open(path,"r")
lines=f.readlines()
result=[]
for x in lines:
    b=x.split()
    if len(b)>2:
      b.pop(1)
    else:
      pass  
    name.append(b[0])

In [ ]:
name

['ID',
 'Delivery_person_ID',
 'Delivery_person_Age',
 'Delivery_person_Ratings',
 'Restaurant_latitude',
 'Restaurant_longitude',
 'Delivery_location_latitude',
 'Delivery_location_longitude',
 'Order_Date',
 'Time_Orderd',
 'Time_Order_picked',
 'Weather',
 'Road_traffic_density',
 'Vehicle_condition',
 'Type_of_order',
 'Type_of_vehicle',
 'multiple_deliveries',
 'Festival',
 'City',
 'Time_taken',
 'Name:']

In [ ]:
result=[]

In [ ]:
my=[]

In [ ]:
my=[]

In [ ]:
n=[]
import glob
for file in glob.glob('/content/dataset/test/*.txt'):
  n.append(file)
  f=open(file,"r")

  lines=f.readlines()
  result=[]
  for x in lines:
    b=x.split()
    if len(b)>2:
      b.pop(1)
    else:
        pass
    result.append(b[1])
  my.append(result)

In [ ]:
my[0][0]

'0x85b0'

In [ ]:
j[0]

'55116'

In [ ]:
 '/content/dataset/test/47070.txt',
 '/content/dataset/test/51944.txt',

In [ ]:
n

In [ ]:
j=[]

In [ ]:
len(j)

11399

In [ ]:
for i in n:
  t=i.split('/')
  y=t[-1]
  m=y.split('.')
  u=m[0]
  j.append(u)

In [ ]:
n

In [ ]:
my[0]

['0xb7dc',
 'BANGRES08DEL03',
 '31.000000',
 '4.200000',
 '12.906229',
 '77.596791',
 '12.936229',
 '77.626791',
 '26-03-2022',
 '23:20',
 '23:25',
 'Stormy',
 'Low',
 '0',
 'Drinks',
 'motorcycle',
 '1.000000',
 'No',
 'Metropolitian',
 'dtype:']

In [ ]:
my=[]
with open('train.csv', 'a') as csv_file:
    for path in glob.glob('/content/dataset/test*.txt'):
        my.append(result)
        with open(path) as txt_file:
            txt = txt_file.readlines()
            
            for x,u in enumerate(txt):
              #print(x)
              b=u.split()
              if len(b)>2:
                #print(b)
                b=b.pop(1)
                #print(b)
              else:
                pass  
              result.append(b[1])

In [ ]:
v

['Sunny', '24.000000', 'dtype:']

In [ ]:
len(s)

21

In [ ]:
name

['ID',
 'Delivery_person_ID',
 'Delivery_person_Age',
 'Delivery_person_Ratings',
 'Restaurant_latitude',
 'Restaurant_longitude',
 'Delivery_location_latitude',
 'Delivery_location_longitude',
 'Order_Date',
 'Time_Orderd',
 'Time_Order_picked',
 'Weather',
 'Road_traffic_density',
 'Vehicle_condition',
 'Type_of_order',
 'Type_of_vehicle',
 'multiple_deliveries',
 'Festival',
 'City',
 'Time_taken',
 'Name:',
 '0x4607',
 'INDORES13DEL02',
 '37.000000',
 '4.900000',
 '22.745049',
 '75.892471',
 '22.765049',
 '75.912471',
 '19-03-2022',
 '11:30',
 '11:45',
 'conditions',
 'High',
 '2',
 'Snack',
 'motorcycle',
 '0.000000',
 'No',
 'Urban',
 '(min)',
 '0,']

In [ ]:
len(txt[1].split())

In [ ]:
import numpy as np

In [ ]:
with open('train.csv', 'a') as csv_file:
    for path in glob.glob('/content/dataset/train/*.txt'):
        with open(path) as txt_file:
            txt = txt_file.readlines()

In [ ]:
y=[1,2,3]
i=[]
i.append(y)

In [ ]:
i

[[1, 2, 3]]

In [ ]:
my=[]
result=[]

In [ ]:
import glob
#result=np.array()
my=[]
with open('train.csv', 'a') as csv_file:
    for path in glob.glob('/content/dataset/train/*.txt'):
        my.append(result)
        with open(path) as txt_file:
            txt = txt_file.readlines()
            
            for x,u in enumerate(txt):
              #print(x)
              b=u.split()
              result.append(b[1])

In [ ]:
import glob
#result=np.array()
my=[]
with open('train.csv', 'a') as csv_file:
    for path in glob.glob('/content/dataset/train/*.txt'):
        my.append(result)
        with open(path) as txt_file:
            txt = txt_file.readlines()
            
            for x,u in enumerate(txt):
              #print(x)
              b=u.split()
              result.append(b[1])

In [ ]:
type(my)

list

In [ ]:
len(my)

45593

In [ ]:
my_array = np.asarray(my)

In [ ]:
my_array.shape

(11399, 20)

In [ ]:
my_array

array([['0xb7dc', 'BANGRES08DEL03', '31.000000', ..., 'No',
        'Metropolitian', 'dtype:'],
       ['0x1adc', 'VADRES02DEL02', '20.00', ..., 'No', 'NaN', 'dtype:'],
       ['0xca5f', 'KOCRES11DEL02', '39.000000', ..., 'No',
        'Metropolitian', 'dtype:'],
       ...,
       ['0x4a0a', 'MYSRES02DEL01', '23.000000', ..., 'No', 'Urban',
        'dtype:'],
       ['0xb845', 'PUNERES07DEL01', '20.000000', ..., 'No',
        'Metropolitian', 'dtype:'],
       ['0x23e9', 'SURRES09DEL01', '30.000000', ..., 'No', 'NaN',
        'dtype:']], dtype='<U17')

In [ ]:
import pandas as pd

In [ ]:
df_test = pd.DataFrame(my_array)

In [ ]:
df_test.columns=['ID',
 'Delivery_person_ID',
 'Delivery_person_Age',
 'Delivery_person_Ratings',
 'Restaurant_latitude',
 'Restaurant_longitude',
 'Delivery_location_latitude',
 'Delivery_location_longitude',
 'Order_Date',
 'Time_Orderd',
 'Time_Order_picked',
 'Weather',
 'Road_traffic_density',
 'Vehicle_condition',
 'Type_of_order',
 'Type_of_vehicle',
 'multiple_deliveries',
 'Festival',
 'City',
 'Name:']

In [ ]:
name

In [ ]:
us=['ID',
 'Delivery_person_ID',
 'Delivery_person_Age',
 'Delivery_person_Ratings',
 'Restaurant_latitude',
 'Restaurant_longitude',
 'Delivery_location_latitude',
 'Delivery_location_longitude',
 'Order_Date',
 'Time_Orderd',
 'Time_Order_picked',
 'Weather',
 'Road_traffic_density',
 'Vehicle_condition',
 'Type_of_order',
 'Type_of_vehicle',
 'multiple_deliveries',
 'Festival',
 'City']

In [ ]:
df_test_n=df_test[us]

In [ ]:
df_test_n.head()

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weather,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City
0,0xb7dc,BANGRES08DEL03,31.000000,4.200000,12.906229,77.596791,12.936229,77.626791,26-03-2022,23:20,23:25,Stormy,Low,0,Drinks,motorcycle,1.000000,No,Metropolitian
1,0x1adc,VADRES02DEL02,20.00,4.70,0.00,0.00,0.08,0.08,16-03-2022,18:55,19:05,Windy,Medium,1,Snack,scooter,0.00,No,NaN
2,0xca5f,KOCRES11DEL02,39.000000,4.900000,10.006881,76.345397,10.056881,76.395397,17-02-2022,18:30,18:45,Windy,Medium,1,Meal,scooter,1.000000,No,Metropolitian
3,0x2fd7,VADRES08DEL03,28.00,4.90,0.00,0.00,0.06,0.06,01-03-2022,23:45,23:60,Cloudy,Low,2,Meal,motorcycle,1.00,No,Metropolitian
4,0x52d1,MYSRES14DEL03,24.00,4.00,0.00,0.00,0.09,0.09,04-04-2022,21:20,21:30,Sunny,Jam,0,Drinks,motorcycle,0.00,No,Metropolitian

In [ ]:
df_test_n.to_csv('test_or.csv',index=False)

In [ ]:
ss=pd.read_csv('/content/dataset/sample_submission.csv')

In [ ]:
ss.to_csv('sa_sub.csv',index=False)

In [ ]:
t=pd.read_csv('/content/drive/MyDrive/hacker_earth/amazon_hiring/train_or.csv')
t.head()

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weather,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken
0,0x1c92,COIMBRES03DEL02,39.0,5.0,11.025083,77.015393,11.045083,77.035393,01-04-2022,9:40,9:45,Sunny,Low,1,Drinks,motorcycle,1.0,No,Metropolitian,19.0
1,0xaaab,VADRES07DEL01,36.0,4.7,0.000000,0.000000,0.070000,0.070000,04-03-2022,19:10,19:20,Stormy,Jam,0,Buffet,motorcycle,3.0,No,Metropolitian,43.0
2,0x463,VADRES20DEL03,NaN,NaN,-22.311358,-73.164798,22.371358,73.224798,03-04-2022,NaN,23:30,NaN,NaN,3,Buffet,electric_scooter,1.0,No,Metropolitian,21.0
3,0xacec,RANCHIRES07DEL01,37.0,4.2,23.359407,85.325055,23.469407,85.435055,02-04-2022,21:45,21:50,Cloudy,Jam,1,Meal,motorcycle,2.0,No,Semi-Urban,46.0
4,0xb9cc,HYDRES01DEL02,38.0,3.7,17.410371,78.437225,17.540371,78.567225,04-04-2022,17:35,17:40,Windy,Medium,2,Snack,electric_scooter,1.0,No,Metropolitian,32.0

In [ ]:
ss

       ID  Time_taken (min)
0  0x7faf              25.0
1  0x4607              24.0
2  0xb379              33.0
3  0x7804              19.0
4  0x20f7              42.0

In [ ]:
df_new=df[us]
df_new.head()

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weather,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken
0,0x1c92,COIMBRES03DEL02,39.000000,5.000000,11.025083,77.015393,11.045083,77.035393,01-04-2022,9:40,9:45,Sunny,Low,1,Drinks,motorcycle,1.000000,No,Metropolitian,19.000000
1,0xaaab,VADRES07DEL01,36.00,4.70,0.00,0.00,0.07,0.07,04-03-2022,19:10,19:20,Stormy,Jam,0,Buffet,motorcycle,3.00,No,Metropolitian,43.00
2,0x463,VADRES20DEL03,NaN,NaN,-22.311358,-73.164798,22.371358,73.224798,03-04-2022,NaN,23:30,NaN,NaN,3,Buffet,electric_scooter,1.000000,No,Metropolitian,21.000000
3,0xacec,RANCHIRES07DEL01,37.000000,4.200000,23.359407,85.325055,23.469407,85.435055,02-04-2022,21:45,21:50,Cloudy,Jam,1,Meal,motorcycle,2.000000,No,Semi-Urban,46.000000
4,0xb9cc,HYDRES01DEL02,38.000000,3.700000,17.410371,78.437225,17.540371,78.567225,04-04-2022,17:35,17:40,Windy,Medium,2,Snack,electric_scooter,1.000000,No,Metropolitian,32.000000

In [ ]:
%cd "/content/drive/MyDrive/hacker_earth/amazon_hiring"

/content/drive/MyDrive/hacker_earth/amazon_hiring

In [ ]:
df_new.to_csv('train_or.csv',index=False)

In [ ]:
import numpy

In [ ]:
my=[]

In [ ]:
import glob
for file in glob.glob('/content/dataset/train/*.txt'):
  f=open(file,"r")
  lines=f.readlines()
  result=[]
  for x in lines:
    b=x.split()
    result.append(b[1])
  my.append(result)

In [ ]:
matrix = numpy.empty(shape=(21, 5), dtype='object')
print(matrix)

In [ ]:
type(result)

list

In [ ]:
   f=open(file,"r")
    lines=f.readlines()
    result=[]
    for x in lines:
      b=x.split()
      result.append(b[])

In [ ]:
file='/content/dataset/train/0.txt'

In [ ]:
len(result)

21

In [ ]:
result

['0x4607',
 'INDORES13DEL02',
 '37.000000',
 '4.900000',
 '22.745049',
 '75.892471',
 '22.765049',
 '75.912471',
 '19-03-2022',
 '11:30',
 '11:45',
 'conditions',
 'High',
 '2',
 'Snack',
 'motorcycle',
 '0.000000',
 'No',
 'Urban',
 '(min)',
 '0,']

In [ ]:
txt

In [ ]:
with open(path) as txt_file:
            txt = txt_file.read()

In [ ]:
txt

In [ ]:
len(contents)

21

In [ ]:
with open(path) as f:
    contents = f.readlines()

In [ ]:
type(contents)

list

In [ ]:
print(i-1)

In [ ]:
len(contents[0].split(' '))

38

In [ ]:
t=contents[0].split(' ')[37]

In [ ]:
t

'0x4607\n'

In [ ]:
for i in contents:
  print(i)

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
from math import sqrt
from lightgbm import LGBMRegressor
import xgboost as xgb
import datetime
from sklearn.preprocessing import LabelEncoder

In [ ]:
ss=pd.read_csv('/content/dataset/sample_submission.csv')
train = pd.read_csv('train.csv' )
test = pd.read_csv('test.csv')

In [ ]:
train.head()

In [ ]:
df

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,...,Weather,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken,Name:
0,0x1c92,COIMBRES03DEL02,39.000000,5.000000,11.025083,77.015393,11.045083,77.035393,01-04-2022,9:40,...,conditions,Low,1,Drinks,motorcycle,1.000000,No,Metropolitian,(min),"4110,"
1,0xaaab,VADRES07DEL01,36.00,4.70,0.00,0.00,0.07,0.07,04-03-2022,19:10,...,conditions,Jam,0,Buffet,motorcycle,3.00,No,Metropolitian,(min),"32400,"
2,0x463,VADRES20DEL03,NaN,NaN,-22.311358,-73.164798,22.371358,73.224798,03-04-2022,NaN,...,conditions,NaN,3,Buffet,electric_scooter,1.000000,No,Metropolitian,(min),"24346,"
3,0xacec,RANCHIRES07DEL01,37.000000,4.200000,23.359407,85.325055,23.469407,85.435055,02-04-2022,21:45,...,conditions,Jam,1,Meal,motorcycle,2.000000,No,Semi-Urban,(min),"20352,"
4,0xb9cc,HYDRES01DEL02,38.000000,3.700000,17.410371,78.437225,17.540371,78.567225,04-04-2022,17:35,...,conditions,Medium,2,Snack,electric_scooter,1.000000,No,Metropolitian,(min),"6410,"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45588,0x6498,HYDRES17DEL01,39.000000,4.700000,17.451976,78.385883,17.461976,78.395883,17-03-2022,10:30,...,conditions,Low,2,Meal,electric_scooter,1.000000,No,Metropolitian,(min),"25158,"
45589,0x839c,VADRES07DEL02,34.00,4.30,0.00,0.00,0.13,0.13,02-04-2022,20:60,...,conditions,Jam,2,Snack,scooter,1.00,No,Metropolitian,(min),"31881,"
45590,0x5b84,RANCHIRES05DEL01,31.000000,4.000000,23.355164,85.324097,23.365164,85.334097,24-03-2022,8:10,...,conditions,Low,0,Meal,motorcycle,1.000000,No,Metropolitian,(min),"22490,"
45591,0x9886,JAPRES18DEL01,36.000000,4.400000,26.913987,75.752891,26.983987,75.822891,29-03-2022,17:40,...,conditions,Medium,2,Meal,scooter,1.000000,No,Metropolitian,(min),"30527,"
45592,0x7f91,VADRES05DEL02,28.000000,4.100000,22.310526,73.170937,22.390526,73.250937,27-03-2022,18:60,...,conditions,Medium,1,Drinks,scooter,1.000000,No,Urban,(min),"22498,"

In [ ]:
df.columns=name

In [ ]:
df[df.ID=='0x4607']

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,...,Weather,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken,Name:
21661,0x4607,INDORES13DEL02,37.000000,4.900000,22.745049,75.892471,22.765049,75.912471,19-03-2022,11:30,...,conditions,High,2,Snack,motorcycle,0.000000,No,Urban,(min),"0,"

In [ ]:
df

In [ ]:
df['Name:']

0         4110,
1        32400,
2        24346,
3        20352,
4         6410,
          ...
45588    25158,
45589    31881,
45590    22490,
45591    30527,
45592    22498,
Name: Name:, Length: 45593, dtype: object